apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotstar-deployment
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotstarapp
  template:
    metadata:
      labels:
        app: hotstarapp
    spec:
      containers:
      - name: hotstarcontainer
        image: dixit7/hotstar:v3
        ports:
        - containerPort: 3000