apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotstar-deployment
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotstarapp
  template:
    metadata:
      labels:
        app: hotstarapp
    spec:
      containers:
      - name: hotstarcontainer
        image: 050515008040.dkr.ecr.us-east-1.amazonaws.com/test-repositories:v21
        ports:
        - containerPort: 3000
