
apiVersion: v1
kind: Service
metadata:
  name: hotstarsvc
  namespace: test
spec:
  type: NodePort
  selector:
    app: hotstarapp
  ports:
  - port: 3001
    targetPort: 3000
    nodePort: 31000